# see: https://github.com/janraasch/hugo-bearblog
theme = 'hugo-bearblog'
baseURL = 'https://blikstiender.com/'
languageCode = 'en-us'
title = 'Blikstiender!'


[permalinks]
  writing = "/:slug/"
  tags = "/blog/:slug"

[[deployment.targets]]
name = "aws"
URL = "s3://blikstiender.com?region=us-east-1"
cloudFrontDistributionID = "E3UL7IZWL6AM0V"
